source ~/venv/bin/activate

python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &
python3 model_init_random.py &