source ~/venv/bin/activate
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
python3 model_init.py &
